name: template
description: Example Flutter app using Flood.
publish_to: none
version: 0.0.3+2
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1

  flood:
    git:
      url: "git@github.com:JLogical-Apps/flood.git"
      ref: v4.0
      path: packages/flood/flood
  template_core:
    path: ../template_core
flutter:
  uses-material-design: true
  assets:
    - assets/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
dependency_overrides:
  http: 0.13.5
  vm_service: 13.0.0