name: template
description: Example Flutter app using JLogical Utils.
publish_to: none
version: 0.0.3+2
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1

  jlogical_utils:
    git:
      url: "git@github.com:jaboyc/jlogical_utils.git"
      ref: v3.3
      path: packages/jlogical_utils/jlogical_utils
  template_core:
    path: ../template_core
flutter:
  uses-material-design: true
  assets:
    - assets/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
dependency_overrides:
  http: 0.13.5
  vm_service: 13.0.0