name: template_core
description: Core
version: 0.0.3+2
publish_to: none
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  collection: ^1.16.0
  intl: ^0.17.0
  meta: ^1.8.0
  jlogical_utils_core:
    git:
      url: "git@github.com:jaboyc/jlogical_utils.git"
      ref: v3.3
      path: packages/jlogical_utils/jlogical_utils_core
  jlogical_utils_cli:
    git:
      url: "git@github.com:jaboyc/jlogical_utils.git"
      ref: v3.3
      path: packages/jlogical_utils/jlogical_utils_cli
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6
dependency_overrides:
  vm_service: 13.0.0